spring.application.name=gestionONG
server.port=8081

spring.datasource.url=jdbc:mariadb://localhost:3306/proyecto
spring.datasource.username=dev
spring.datasource.password=dev

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=c2VjcmV0b011eUZ1ZXJ0ZVBhcmFKV1Rlbkdlc3Rpb25PTkc=
jwt.expiration=86400000

spring.jackson.mapper.accept-case-insensitive-enums=true

logging.level.org.springframework.security=TRACE